### ISSUE TITLE
[Request] Bungeecord "send" option.

### ISSUE THREAD

**Issue by BiGUNMAN** [messageofdeath/CommandNPC#1]
So this is a request more then anything, and it would be awesome to see it added at some point to CommandNPC. Basically when configured (a true/false option in config), you can add /server [bungee_server_name] as a "player executed command", and it will send the user to the configured server. (As its a bungeecord command it doesn't actually execute).

It would also be nice to have the "player" type NPC's to execute commands on right/left click. Rather then only right click as they do currently.

**Comment by messageofdeath** [comment]
I know this is a really really, late response. I'm not too familiar with bungeecord, but couldn't you set it up where it player executes the command by **NOT** using the flag [-c for console]. It currently has the player chat out the message so it simulates like they are actually typing the message. (Don't even know if you still use this anymore)

**Comment by BiGUNMAN** [comment]
Lol, insanely late reply. I had someone modify the plugin for me so that
when typing 'server (server)' as the command, it would send players to the
specified server.

**Comment by messageofdeath** [comment]
If your able to send that version of the file I'd be very grateful as I don't know BungeeCord or have the means to test it. Like I said it's up to you. (Also I just got back into doing this, that is why the late response lol)

**Comment by BiGUNMAN** [comment]
Here's the source:
[_aspiria-commandnpc-6d601e92e6a9.zip](https://github.com/messageofdeath/CommandNPC/files/969305/_aspiria-commandnpc-6d601e92e6a9.zip)

Nice to see it on SpigotMC https://www.spigotmc.org/resources/commandnpc.40295/ :)

**Comment by messageofdeath** [comment]
Thanks! I'll look into the code and see about implementing it into the full plugin!

**Comment by messageofdeath** [comment]
Will be implemented in v1.8.7.
Download link with all the new commands plus bungeecord support.
