### ISSUE TITLE
Re Commands Dont Work

### ISSUE THREAD

**Issue by TacoCraft** [messageofdeath/CommandNPC#10]
I set the cmd to the npc and when I click the npc it just gives the "Unknown command. Type "/help" for help. Ive tried with very simple commands like /msg, /say, /tp, /help and nothing works. The latest version doesnt work with 1.8

**Comment by messageofdeath** [comment]
Can you list all of the plugins that are on your server? Currently you are the only one having this issue. Are you running spigot or craftbukkit?
