### ISSUE TITLE
No permissons NPC

### ISSUE THREAD

**Issue by Stickmen1** [messageofdeath/CommandNPC#12]
Hello, I want to people don't need any permissons to run a command with citizen. And I wrote the command: /npc cmdadd noperm (the command name). But if I try there is "You have no permissions to run this command. How to fix that?

**Comment by messageofdeath** [comment]
CommandNPC doesn't add any permissions to the command unless specified with the flag '--p'. The error message is coming from the plug-in that the command originates from. You have three choices from here. 1) Use the flag '-c' to run the command in console (if applicable to the type of command)
2) Use the flag '-o' to give the player op to run the command then remove it right away
3) Give the player explicit permission to run the command
