### ISSUE TITLE
Error minecraft 1.11.2 [TacoSpigot / PaperSpigot]

### ISSUE THREAD

**Issue by EverNife** [messageofdeath/CommandNPC#3]
On command `npc add`
https://hastebin.com/owolobipig.md

On command `/commandnpc`
https://hastebin.com/jacanecufo.vbs

Tested on PaperSpigo, occurs the same:

On command `npc add`
https://hastebin.com/uzotateziz.md

On command `/commandnpc`
https://hastebin.com/izufeziliq.vbs

**Comment by evernife** [comment]
Confirmed, changed to PaperSpigot and there was no problems, seems to be more like a TacoSpigot problem...

**Comment by messageofdeath** [comment]
I'm currently looking into the issue. I was testing and found this error. Don't know what caused it. Get back soon.

**Comment by messageofdeath** [comment]
I've fixed this issue.
Fixed: cmdadd would set ClickType to null by default and when you don't use '--t clickType' it would throw null.

**Comment by messageofdeath** [comment]
Download Link: https://drive.google.com/open?id=0B2DinQ8zWpStY1Atb2xXMWcyT2M
