### ISSUE TITLE
Left-Click not working?

### ISSUE THREAD

**Issue by MuddledGuy** [messageofdeath/CommandNPC#4]
I am trying to left-click my NPC to run a command. I am running version 1.8.7, on the Paper version 1.11.2.

I have set it to both when doing /npc cmdadd --f Both time - and in my config.yml file. Right-click works fine, however left-click does not work at all.

![s4x4slj](https://i.imgur.com/S4X4sLj.png)

**Comment by messageofdeath** [comment]
Is the NPC a villager? If so, what other plugins do you have?

**Comment by MuddledGuy** [comment]
The NPC is a default NPC with a set skin. I have a lot of plugins, however not any that I think would cause an issue. Major one is Featherboard. I will look in a few hours and list more plugins.

I suppose I might just have to disable every plugin one by one.

**Comment by messageofdeath** [comment]
I'm thinking this has to be an issue with the incompatibility between this plugin and another as there is no one else having this issue. And this would be a major issue if it were lol

**Comment by MuddledGuy** [comment]
So I have looked at all my plugin, and they are all pretty basic, and I don't believe I have any plugins that do anything with the hand either. -with the exception of a plugin I coded for player information, however, it only checks when the command is run.

Do you have a list of possible known issues with plugins?

**Comment by messageofdeath** [comment]
I honestly have no idea why it wouldn't work. The only plugin so far that has caused conflict with this is 'Bar Gamble,' and that's why I asked if you used a Villager as the NPC.

**Comment by ShawnPR1** [comment]
I know this thread is closed and very old, but I ran into the same problem. For me it was Multiverse-Core causing this issue.

To fix it, stand in the world where you want the NPC's left click command to work and type
`/mvm set pvp true`

If you still want PVP to be disabled in the entire world, use worldguard and type
`/rg flag __global__ pvp deny`

Left click then works as intended.
