### ISSUE TITLE
Plugin Not Working Properly

### ISSUE THREAD

**Issue by TacoCraft** [messageofdeath/CommandNPC#5]
I set the cmd to the npc and when I click the npc it just gives the "Unknown command. Type "/help" for help. Ive tried with very simple commands like /msg, /say, /tp, /help and nothing works

**Comment by messageofdeath** [comment]
When typing out the command in the command 'cmdadd' or 'cmdset', do not include a '/' as this is done while it's executing the command. Now if the command requires an additional '/' like those in WorldEdit, then it is okay to add one.

**Comment by TacoCraft** [comment]
I tried that just now using the command '/npc addcmd false noperm say test' and it didnt work

**Comment by messageofdeath** [comment]
Make sure to download the latest version of CommandNPC.
the command is '/npc cmdadd [-c console] [-o op] [--v price] [--t clickType] [--d delay] [--p perm] <command>'
With this new command you can use every single item in [] or none of them, but make sure to have your command at the end. Anything that has two (-) like [--v price] require additional input. So for '--v' you would input '--v 320'. For any that have one (-) like '-c', you would simply put '-c' to set that option to true.

**Comment by TacoCraft** [comment]
The latest version doesnt work with my 1.8.8 server
