### ISSUE TITLE
Add command wont perform

### ISSUE THREAD

**Issue by Audasii** [messageofdeath/CommandNPC#6]
Everytime I add a command to an NPC it tells me that I can't perform that command at this time? Any suggestions?

**Comment by messageofdeath** [comment]
Was the command already added to the NPC, and then after the command was executed, then it said that? If so, that's the plugin with the command, not this one.

**Comment by Audasii** [comment]
Yea, I had added a warp command, and then it came up with that message

**Comment by messageofdeath** [comment]
What's the exact message word for word that you are receiving?

**Comment by Audasii** [comment]
currently all it's saying is "You cannot do this yet!"

**Comment by messageofdeath** [comment]
Currently, I have a cooldown setting in the config.yml. It is set to '20' ticks. So the cooldown, should only last 1 second. Is it lasting longer than that?

**Comment by Audasii** [comment]
Yea, the command goes through. I'm not really sure why, I've been messing with it for awhile now. Would you possibly mind recommending the command to use in order to allow a warp through the npc?

**Comment by Audasii** [comment]
When I right click the npc to perform the task it just says that its an unknown command and that I cant do it yet

**Comment by messageofdeath** [comment]
What's the server ip? Let me try it out

**Comment by Audasii** [comment]
well currently you have to use a hamachi, we haven't bought our server host yet. Is that ok? I know it's a bit noobish

**Comment by messageofdeath** [comment]
That's fine

**Comment by Audasii** [comment]
Alright
Username: Audasii
Password: Audasii
Thanks so much for the help btw

**Comment by messageofdeath** [comment]
Resolved.
