### ISSUE TITLE
Unknown Command

### ISSUE THREAD

**Issue by xPacco** [messageofdeath/CommandNPC#7]
When I add a multiverse command with to my npc it teleports me there but says unknown command

**Comment by messageofdeath** [comment]
What's the exact command you used?

**Comment by messageofdeath** [comment]
Use the command '/npc cmdinfo' There might be another command running that you added that you forgot about that isn't valid.

**Comment by xPacco** [comment]
I checked and it only said the 1 command I used "/mvtp a:tntrun"

**Comment by messageofdeath** [comment]
If you have the '/' in the command remove it. Don't know why it would say Unknown command, if you don't have the '/' in the command. Yet it still teleported you there.
